var searchData=
[
  ['tag_0',['10. Tag the release in the local repository with a signed tag',['../md_doc_2internal_2release-github.html#autotoc_md18',1,'']]],
  ['tag_20and_20upload_20the_20following_20files_1',['16. Create a new GitHub release using the associated tag and upload the following files',['../md_doc_2internal_2release-github.html#autotoc_md24',1,'']]],
  ['tag_20the_20release_20in_20the_20local_20repository_20with_20a_20signed_20tag_2',['10. Tag the release in the local repository with a signed tag',['../md_doc_2internal_2release-github.html#autotoc_md18',1,'']]],
  ['tag_20to_20the_20main_20github_20repository_3',['15. Push the release tag to the main GitHub repository',['../md_doc_2internal_2release-github.html#autotoc_md23',1,'']]],
  ['tarball_4',['tarball',['../md_doc_2internal_2release-github.html#autotoc_md19',1,'11. Build final release tarball'],['../md_doc_2internal_2release-github.html#autotoc_md21',1,'13. Generate a checksum for the release tarball']]],
  ['tarball_20and_20checksum_20using_20the_20maintainer_20s_20key_5',['14. GPG sign the release tarball and checksum using the maintainer&apos;s key',['../md_doc_2internal_2release-github.html#autotoc_md22',1,'']]],
  ['tarball_20in_20a_20separate_20directory_6',['12. Verify the release tarball in a separate directory',['../md_doc_2internal_2release-github.html#autotoc_md20',1,'']]],
  ['tasks_7',['4. Manipulation with tasks',['../group__group__tasks.html',1,'']]],
  ['test_20builds_8',['6. Perform any distribution test builds',['../md_doc_2internal_2release-github.html#autotoc_md14',1,'']]],
  ['test_20suite_20for_20libcgroup_9',['Functional Test Suite for libcgroup',['../md_tests_2ftests_2README.html',1,'']]],
  ['test_20suite_20runs_20without_20error_10',['3. Verify that the bundled test suite runs without error',['../md_doc_2internal_2release-github.html#autotoc_md11',1,'']]],
  ['test_20your_20code_20using_20existing_20tests_11',['Test Your Code Using Existing Tests',['../md_CONTRIBUTING.html#autotoc_md1',1,'']]],
  ['tests_12',['Test Your Code Using Existing Tests',['../md_CONTRIBUTING.html#autotoc_md1',1,'']]],
  ['tests_20for_20new_20functionality_13',['Add New Tests for New Functionality',['../md_CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['that_20all_20issues_20assigned_20to_20the_20release_20milestone_20have_20been_20resolved_14',['1. Verify that all issues assigned to the release milestone have been resolved',['../md_doc_2internal_2release-github.html#autotoc_md9',1,'']]],
  ['that_20resulted_20in_20code_20changes_20restart_20the_20process_15',['7. If any problems were found up to this point that resulted in code changes, restart the process',['../md_doc_2internal_2release-github.html#autotoc_md15',1,'']]],
  ['that_20the_20bundled_20test_20suite_20runs_20without_20error_16',['3. Verify that the bundled test suite runs without error',['../md_doc_2internal_2release-github.html#autotoc_md11',1,'']]],
  ['that_20the_20github_20actions_20are_20all_20passing_17',['2. Verify that the Github Actions are all passing',['../md_doc_2internal_2release-github.html#autotoc_md10',1,'']]],
  ['that_20the_20packaging_20is_20correct_18',['4. Verify that the packaging is correct',['../md_doc_2internal_2release-github.html#autotoc_md12',1,'']]],
  ['that_20there_20are_20no_20outstanding_20defects_20from_20coverity_19',['5. Verify that there are no outstanding defects from Coverity',['../md_doc_2internal_2release-github.html#autotoc_md13',1,'']]],
  ['the_20associated_20tag_20and_20upload_20the_20following_20files_20',['16. Create a new GitHub release using the associated tag and upload the following files',['../md_doc_2internal_2release-github.html#autotoc_md24',1,'']]],
  ['the_20bundled_20test_20suite_20runs_20without_20error_21',['3. Verify that the bundled test suite runs without error',['../md_doc_2internal_2release-github.html#autotoc_md11',1,'']]],
  ['the_20community_22',['Interacting with the Community',['../md_CONTRIBUTING.html#autotoc_md0',1,'']]],
  ['the_20following_20files_23',['16. Create a new GitHub release using the associated tag and upload the following files',['../md_doc_2internal_2release-github.html#autotoc_md24',1,'']]],
  ['the_20github_20actions_20are_20all_20passing_24',['2. Verify that the Github Actions are all passing',['../md_doc_2internal_2release-github.html#autotoc_md10',1,'']]],
  ['the_20github_20release_20notes_20for_20older_20releases_20which_20are_20now_20unsupported_25',['17. Update the GitHub release notes for older releases which are now unsupported',['../md_doc_2internal_2release-github.html#autotoc_md25',1,'']]],
  ['the_20libcgroup_20project_26',['How to Contribute to the libcgroup Project',['../md_CONTRIBUTING.html',1,'']]],
  ['the_20libcgroup_20release_20process_27',['The libcgroup Release Process',['../md_doc_2internal_2release-github.html',1,'']]],
  ['the_20libcgroup_20security_20vulnerability_20handling_20process_28',['The libcgroup Security Vulnerability Handling Process',['../md_SECURITY.html',1,'']]],
  ['the_20local_20repository_20with_20a_20signed_20tag_29',['10. Tag the release in the local repository with a signed tag',['../md_doc_2internal_2release-github.html#autotoc_md18',1,'']]],
  ['the_20main_20github_20repository_30',['15. Push the release tag to the main GitHub repository',['../md_doc_2internal_2release-github.html#autotoc_md23',1,'']]],
  ['the_20maintainer_20s_20key_31',['14. GPG sign the release tarball and checksum using the maintainer&apos;s key',['../md_doc_2internal_2release-github.html#autotoc_md22',1,'']]],
  ['the_20packaging_20is_20correct_32',['4. Verify that the packaging is correct',['../md_doc_2internal_2release-github.html#autotoc_md12',1,'']]],
  ['the_20process_33',['7. If any problems were found up to this point that resulted in code changes, restart the process',['../md_doc_2internal_2release-github.html#autotoc_md15',1,'']]],
  ['the_20release_20in_20the_20local_20repository_20with_20a_20signed_20tag_34',['10. Tag the release in the local repository with a signed tag',['../md_doc_2internal_2release-github.html#autotoc_md18',1,'']]],
  ['the_20release_20milestone_20have_20been_20resolved_35',['1. Verify that all issues assigned to the release milestone have been resolved',['../md_doc_2internal_2release-github.html#autotoc_md9',1,'']]],
  ['the_20release_20tag_20to_20the_20main_20github_20repository_36',['15. Push the release tag to the main GitHub repository',['../md_doc_2internal_2release-github.html#autotoc_md23',1,'']]],
  ['the_20release_20tarball_37',['13. Generate a checksum for the release tarball',['../md_doc_2internal_2release-github.html#autotoc_md21',1,'']]],
  ['the_20release_20tarball_20and_20checksum_20using_20the_20maintainer_20s_20key_38',['14. GPG sign the release tarball and checksum using the maintainer&apos;s key',['../md_doc_2internal_2release-github.html#autotoc_md22',1,'']]],
  ['the_20release_20tarball_20in_20a_20separate_20directory_39',['12. Verify the release tarball in a separate directory',['../md_doc_2internal_2release-github.html#autotoc_md20',1,'']]],
  ['the_20version_20number_20in_20configure_20ac_20ac_5finit_20macro_20and_20library_20version_20macros_40',['9. Update and commit the version number in configure.ac AC_INIT(...) macro and LIBRARY version macros',['../md_doc_2internal_2release-github.html#autotoc_md17',1,'']]],
  ['there_20are_20no_20outstanding_20defects_20from_20coverity_41',['5. Verify that there are no outstanding defects from Coverity',['../md_doc_2internal_2release-github.html#autotoc_md13',1,'']]],
  ['this_20is_20a_20new_20major_20minor_20release_20create_20new_20release_20x_20y_20branch_42',['8. If this is a new major/minor release, create new &apos;release-X.Y&apos; branch',['../md_doc_2internal_2release-github.html#autotoc_md16',1,'']]],
  ['this_20point_20that_20resulted_20in_20code_20changes_20restart_20the_20process_43',['7. If any problems were found up to this point that resulted in code changes, restart the process',['../md_doc_2internal_2release-github.html#autotoc_md15',1,'']]],
  ['to_20contribute_20to_20the_20libcgroup_20project_44',['How to Contribute to the libcgroup Project',['../md_CONTRIBUTING.html',1,'']]],
  ['to_20the_20libcgroup_20project_45',['How to Contribute to the libcgroup Project',['../md_CONTRIBUTING.html',1,'']]],
  ['to_20the_20main_20github_20repository_46',['15. Push the release tag to the main GitHub repository',['../md_doc_2internal_2release-github.html#autotoc_md23',1,'']]],
  ['to_20the_20release_20milestone_20have_20been_20resolved_47',['1. Verify that all issues assigned to the release milestone have been resolved',['../md_doc_2internal_2release-github.html#autotoc_md9',1,'']]],
  ['to_20this_20point_20that_20resulted_20in_20code_20changes_20restart_20the_20process_48',['7. If any problems were found up to this point that resulted in code changes, restart the process',['../md_doc_2internal_2release-github.html#autotoc_md15',1,'']]],
  ['todo_20list_49',['Todo List',['../todo.html',1,'']]],
  ['type_50',['type',['../structcgroup__file__info.html#a955506601f440d05cb11e4ee6b455c55',1,'cgroup_file_info']]]
];
