.\" Copyright IBM Corporation. 2009.
.\" Written by Dhaval Giani <dhaval@linux.vnet.ibm.com>.

.TH CGCLEAR  1 2009-10-23 "Linux" "libcgroup Manual"
.SH NAME
cgclear \- unload the cgroup filesystem

.SH SYNOPSIS
\fBcgclear\fR [\fB-e\fR] [\fB-l\fR <\fIfilename\fR>] [\fB-L\fR <\fIdirectory\fR>] [...]

.SH DESCRIPTION

Without parameters, this command moves all the tasks inside the various cgroups
to the root cgroup, deletes all the cgroups and finally
unmounts the cgroup filesystem from the system.

If one or more config files are specified, only groups defined in the config
files are removed. The files are processed in reverse order, i.e. the last
file on command line is processed first, so \fBcgclear\fR can have the same
command line arguments as appropriate \fBcgconfigparser\fR.

.TP
.B -l, --load=<filename>
specifies the config file to read. This option can be used multiple times and
can be mixed with \fB-L\fR option.

.TP
.B -L, --load-directory=<directory>
specifies the directory, which is searched for configuration files. All files
in this directory will be processed in alphabetical order as they were specified
by \fB-l\fR option. This option can be used multiple times and
can be mixed with \fB-l\fR option.

.TP
.B -e
specifies that only empty groups should be removed. If a group defined in a
config file has tasks inside or has a subgroup, it won't be removed. This
option works only with \fB-l\fR or \fB-L\fR options.

.SH SEE ALSO
cgconfigparser(1)
